sudo: required

servies:
  - docker

before_install:
  - docker build -t ahmed-shakeel/docker-react -f dockerfile.dev .

scripts:
  - docker run -e CI=TRUE ahmed-shakeel/docker-react npm run test -- --coverage